name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4', '4.0' ]
        database: [ 'mysql2', 'postgresql', 'sqlite3', 'trilogy' ]
        exclude:
          - ruby: '2.6'
            database: 'trilogy'
          - ruby: '2.7'
            database: 'trilogy'

    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: combustion
          POSTGRES_DB: combustion
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: combustion
          MYSQL_DATABASE: combustion
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up Appraisal
        env:
          BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
        run: bundle exec appraisal update
      - name: Test
        env:
          BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
          CI: "true"
          DB_ADAPTER: ${{ matrix.database }}
          DB_USERNAME: root
          DB_PASSWORD: combustion
          DB_HOST: 127.0.0.1
        run: bundle exec appraisal rspec

  rubocop:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: 2.3.12
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
